# Generated by Django 2.0.4 on 2022-09-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': '詳細', 'verbose_name_plural': '詳細'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Detail'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Item', verbose_name='商品'),
        ),
    ]
